name: SonarCloud

on:
  push:
    branches:
      - master

permissions: read-all

jobs:
  build:
    if: github.repository_owner == 'mybatis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          cache: maven
          distribution: temurin
          java-version: 21
      - name: Start Redis
        uses: shogo82148/actions-setup-redis@v1.43.0
        with:
          redis-version: latest
      - name: Analyze with SonarCloud
        run: ./mvnw verify jacoco:report sonar:sonar -B -V -Dsonar.projectKey=mybatis_redis-cache -Dsonar.organization=mybatis -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN -Dlicense.skip=true --no-transfer-progress -Dsonar.scanner.skipJreProvisioning=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
